name: Compliance Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compliance:
    uses: PandaNetOS/.github/.github/workflows/compliance.yml@main
    secrets: inherit